import 'package:flutter/material.dart';

class LocalizationService {
  static final ValueNotifier<Locale> localeNotifier = ValueNotifier(
    const Locale('en'),
  );

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Dataset Hub',
      'feature_selection_title': 'Dataset Hub',
      'feature_selection_subtitle': 'AI Data Collection Tool',
      'classification_title': 'Image Classification',
      'classification_subtitle': 'Organize images into class folders',
      'detection_title': 'Object Detection',
      'detection_subtitle': 'Bounding boxes for objects',
      'pose_title': 'Pose Estimation',
      'pose_subtitle': 'Body landmarks detection',
      'segmentation_title': 'Segmentation',
      'segmentation_subtitle': 'Pixel-level classification',
      'coming_soon': 'Coming Soon',
      'mobile_collector_title': 'Mobile Data Collector',
      'mobile_collector_desc':
          'Capture, process, and organize your datasets directly on your device. Ready for AI training.',

      'data_capture_title': 'Data Capture',
      'data_capture_subtitle': 'Capture images using camera',
      'dataset_processing_title': 'Dataset Processing',
      'dataset_processing_subtitle': 'Pre-process captured data',
      'dataset_structuring_title': 'Dataset Structuring',
      'dataset_structuring_subtitle': 'Organize and export',
      'captured_datasets': 'Captured Datasets',
      'no_datasets': 'No datasets found',
      'tap_to_start': 'Tap "Data Capture" to start collecting images.',
      'calculating': 'Calculating...',
      'images': 'images',
      'delete_title': 'Delete Datasets',
      'delete_confirm':
          'Are you sure you want to delete selected folder(s)? This cannot be undone.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'selected': 'Selected',
      'items': 'items',
      'configure_dataset': 'Configure Dataset',
      'new_dataset': 'New Dataset',
      'setup_params': 'Set up your data capture parameters.',
      'dataset_name': 'Dataset Name',
      'enter_name_hint': 'e.g., Cat_Faces',
      'capture_quality': 'Capture Quality',
      'save_resolution': 'Save Resolution',
      'burst_mode': 'Burst Mode',
      'photos_per_tap': 'Photos per tap',
      'start_stream': 'Start Stream Capture',
      'enter_name_error': 'Please enter a dataset name',
      'low_quality': 'Low Quality (Fast)',
      'medium_quality': 'Medium Quality (Standard)',
      'high_quality': 'High Quality (HD)',
      'very_high_quality': 'Very High Quality (Full HD)',
      'resolution_hint': 'Final image size in pixels.',
      'processing_title': 'Data Processing',
      'select_dataset': 'Select Dataset Folder',
      'preprocessing': 'Preprocessing',
      'resize_images': 'Resize Images',
      'automated_labeling': 'Automated Labeling',
      'normalize_filenames': 'Normalize Filenames',
      'generate_csv': 'Generate Label CSV',
      'generate_yolo': 'Generate YOLO Labels',
      'data_split': 'Data Split',
      'enable_splitting': 'Enable Splitting',
      'augmentation': 'Augmentation',
      'enable_augmentation': 'Enable Augmentation',
      'start_processing': 'Start Data Processing',
      'processing_complete': 'Processing complete!',

      // Structuring
      'structuring_title': 'Dataset Structuring',
      'generate_metadata': 'Generate Metadata (classes.txt)',
      'export_zip': 'Export to Zip',
      'run_structuring': 'Run Structuring',
      'structuring_complete': 'Structuring complete! Saved to',

      // Viewer
      'delete_images': 'Delete Images',
      'delete_confirmation': 'Are you sure you want to delete',
      'no_images': 'No images found',

      // Data Capture Screen (Ensure no duplicates)
      'burst_shots': 'Shots',
      'single_shot': 'Single Shot',
      'processing_images': 'Processing images...',
      'saved_images': 'Saved images to',
      'quality': 'Quality',
      'retake': 'Retake',
      'save': 'Save',
      'no_cameras': 'No cameras found',
      'camera_init_error': 'Error initializing camera',
      'capture_error': 'Error capturing image',
      'saving': 'Saving...',
    },
    'id': {
      'app_title': 'Pusat Dataset',
      'feature_selection_title': 'Pusat Dataset',
      'feature_selection_subtitle': 'Alat Pengumpulan Data AI',
      'classification_title': 'Klasifikasi Gambar',
      'classification_subtitle': 'Atur gambar ke dalam folder kelas',
      'detection_title': 'Deteksi Objek',
      'detection_subtitle': 'Kotak pembatas untuk objek',
      'pose_title': 'Estimasi Pose',
      'pose_subtitle': 'Deteksi titik tubuh',
      'segmentation_title': 'Segmentasi',
      'segmentation_subtitle': 'Klasifikasi tingkat piksel',
      'coming_soon': 'Segera Hadir',
      'mobile_collector_title': 'Pengumpul Data Seluler',
      'mobile_collector_desc':
          'Ambil, proses, dan atur dataset Anda langsung di perangkat. Siap untuk pelatihan AI.',
      'data_capture_title': 'Pengambilan Data',
      'data_capture_subtitle': 'Ambil gambar menggunakan kamera',
      'dataset_processing_title': 'Pemrosesan Dataset',
      'dataset_processing_subtitle': 'Pra-proses data yang diambil',
      'dataset_structuring_title': 'Penyusunan Dataset',
      'dataset_structuring_subtitle': 'Atur dan ekspor',
      'captured_datasets': 'Dataset Tersimpan',
      'no_datasets': 'Tidak ada dataset ditemukan',
      'tap_to_start': 'Ketuk "Pengambilan Data" untuk mulai.',
      'calculating': 'Menghitung...',
      'images': 'gambar',
      'delete_title': 'Hapus Dataset',
      'delete_confirm':
          'Apakah Anda yakin ingin menghapus folder yang dipilih? Ini tidak bisa dibatalkan.',
      'cancel': 'Batal',
      'delete': 'Hapus',
      'selected': 'Dipilih',
      'items': 'item',
      'configure_dataset': 'Konfigurasi Dataset',
      'new_dataset': 'Dataset Baru',
      'setup_params': 'Atur parameter pengambilan data Anda.',
      'dataset_name': 'Nama Dataset',
      'enter_name_hint': 'misal: Wajah_Kucing',
      'capture_quality': 'Kualitas Tangkapan',
      'save_resolution': 'Resolusi Simpan',
      'burst_mode': 'Mode Beruntun',
      'photos_per_tap': 'Foto per ketukan',
      'start_stream': 'Mulai Tangkapan Stream',
      'enter_name_error': 'Mohon masukkan nama dataset',
      'low_quality': 'Kualitas Rendah (Cepat)',
      'medium_quality': 'Kualitas Sedang (Standar)',
      'high_quality': 'Kualitas Tinggi (HD)',
      'very_high_quality': 'Kualitas Sangat Tinggi (Full HD)',
      'resolution_hint': 'Ukuran gambar akhir dalam piksel.',
      'processing_title': 'Pemrosesan Data',
      'select_dataset': 'Pilih Folder Dataset',
      'preprocessing': 'Pra-pemrosesan',
      'resize_images': 'Ubah Ukuran Gambar',
      'automated_labeling': 'Pelabelan Otomatis',
      'normalize_filenames': 'Normalisasi Nama File',
      'generate_csv': 'Buat Label CSV',
      'generate_yolo': 'Buat Label YOLO',
      'data_split': 'Pemisahan Data',
      'enable_splitting': 'Aktifkan Pemisahan',
      'augmentation': 'Augmentasi',
      'enable_augmentation': 'Aktifkan Augmentasi',
      'start_processing': 'Mulai Pemrosesan Data',
      'processing_complete': 'Pemrosesan selesai!',

      // Structuring
      'structuring_title': 'Penyusunan Dataset',
      'generate_metadata': 'Buat Metadata (classes.txt)',
      'export_zip': 'Ekspor ke Zip',
      'run_structuring': 'Jalankan Penyusunan',
      'structuring_complete': 'Penyusunan selesai! Disimpan di',

      // Viewer
      'delete_images': 'Hapus Gambar',
      'delete_confirmation': 'Apakah Anda yakin ingin menghapus',
      'no_images': 'Tidak ada gambar ditemukan',

      // Data Capture Screen
      'burst_shots': 'Foto',
      'single_shot': 'Satu Foto',
      'processing_images': 'Memproses gambar...',
      'saved_images': 'Gambar disimpan ke',
      'quality': 'Kualitas',
      'retake': 'Ulangi',
      'save': 'Simpan',
      'no_cameras': 'Kamera tidak ditemukan',
      'camera_init_error': 'Kesalahan inisialisasi kamera',
      'capture_error': 'Gagal mengambil gambar',
      'saving': 'Menyimpan...',
    },
  };

  static String get(String key) {
    return _localizedValues[localeNotifier.value.languageCode]?[key] ?? key;
  }

  static void changeLocale(Locale locale) {
    localeNotifier.value = locale;
  }
}
